### PR TITLE
Add table name option to | teragrep exec bloom

### PR DESCRIPTION
**Pull request by 51-code**
Related to PTH-10 issue [410](https://github.com/teragrep/pth_10/issues/410).

Adds an optional parameter for the table name. PTH-10 is responsible for parsing and will throw an exception with a descriptive message if the table name is not given.

### CODE REVIEW

**Comment by 51-code** [comment]
Will be adding regex to the command as well, converted to a draft PR.

**Comment by elliVM** [comment]
Will aim to move options used by command to dpl including regex

**Review by eemhu — APPROVED** [review]
Looks good to me, however perhaps a new issue could be made of unifying the parameters to include `=` signs like in other commands. Also, the order of parameters must match the grammar and can't be given in any other order.

**Comment by elliVM** [comment]
#88 Issue about parameter `=` signs

**Review by kortemik — APPROVED** [review]

**Pull request merged**
